### ISSUE TITLE
Invalid open options

### ISSUE THREAD

**Issue by khanghugo** [advancedfx/afx-blender-scripts#44]
Trying to import .cam file in Blender 3.5.1.

Simply removing the "U" flag works for me.

```
bpy.data.window_managers["WinMan"].addon_search = ""
Python: Traceback (most recent call last):
  File "/home/khang/.config/blender/3.5/scripts/addons/advancedfx/import_cam.py", line 64, in execute
    ok = self.readCam(context)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/khang/.config/blender/3.5/scripts/addons/advancedfx/import_cam.py", line 129, in readCam
    file = open(self.filepath, 'rU')
           ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
Error report with 1 Errors and 0 Warnings
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.delete()
Python: Traceback (most recent call last):
  File "/home/khang/.config/blender/3.5/scripts/addons/advancedfx/import_cam.py", line 64, in execute
    ok = self.readCam(context)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/khang/.config/blender/3.5/scripts/addons/advancedfx/import_cam.py", line 129, in readCam
    file = open(self.filepath, 'rU')
           ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
```

**Comment by dtugend** [comment]
Thank you: https://github.com/advancedfx/afx-blender-scripts/releases/tag/v1.14.3
